// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzQu8vRhpr3chmyx0cdMXDI4avCSfKdmE',
    appId: '1:132676229720:web:853c194a9366949b2d082d',
    messagingSenderId: '132676229720',
    projectId: 'event-management-252b8',
    authDomain: 'event-management-252b8.firebaseapp.com',
    storageBucket: 'event-management-252b8.appspot.com',
    measurementId: 'G-2G93YWWVV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCyRqikwT7IKHKuMSPFNsC423exdSKFHc',
    appId: '1:132676229720:android:613b48e590cea8862d082d',
    messagingSenderId: '132676229720',
    projectId: 'event-management-252b8',
    storageBucket: 'event-management-252b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvI0SKlEhEhSV8F9sde6mZITXiZCsnhYI',
    appId: '1:132676229720:ios:e21844edd5616f1b2d082d',
    messagingSenderId: '132676229720',
    projectId: 'event-management-252b8',
    storageBucket: 'event-management-252b8.appspot.com',
    iosBundleId: 'com.example.eventSports',
  );
}
